// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zueclctjoppubuvherhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZWNsY3Rqb3BwdWJ1dmhlcmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDUwMDcsImV4cCI6MjA2MDU4MTAwN30.6WQ_TInNNzGFLCiOEo3Uq8cR2CT7iVUmkUmIuMwdMb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);